version: '3'
services:
    alerting:
      build: ./alerting
      image: "alerting"
      container_name: infrac-stak-alerting
      restart: unless-stopped
      stdin_open: true
      tty:  true
      privileged: false
      ports:
        - "1000:80/tcp"
        - "1010:443/tcp"
        - "1020:9090/tcp"
    boards:
      build: ./boards
      image: "boards"
      container_name: infrac-stak-board
      restart: unless-stopped
      stdin_open: true
      tty:  true
      privileged: false
      ports:
        - "1030:80/tcp"
        - "1040:8080/tcp"
        - "1050:443/tcp"
    ci:
      build: ./ci
      image: "ci"
      container_name: infrac-stak-ci
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
       - ACCEPT_EULA=Y
      ports:
        - "1060:8080/tcp"
        - "1070:443/tcp"
    dhcp:
      build: ./dhcp
      image: "dhcp"
      container_name: infrac-stak-dhcp
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1080:67/udp"
        - "1090:68/udp"
    dns:
      build: ./dns
      image: "dns"
      container_name: infrac-stak-dns
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1100:53/tcp"
        - "1110:56/tcp"
        - "1120:8080/tcp"
        - "1130:8443/tcp"
    git:
      build: ./git
      image: "git"
      container_name: infrac-stak-git
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1140:3306/tcp"
        - "1150:22/tcp"
        - "1160:80/tcp"
        - "1170:443/tcp"
    java-server:
      build: ./java-server
      image: "java-server"
      container_name: infrac-stak-java-server
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1180:8080/tcp"
        - "1190:8443/tcp"
    ldap:
      build: ./ldap
      image: "ldap"
      container_name: infrac-stak-ldap
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1200:389/tcp"
        - "1210:636/tcp"
    logging:
      build: ./logging
      image: "logging"
      container_name: infrac-stak-logging
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1220:9000/tcp"
        - "1230:443/tcp"
        - "1240:27017/tcp"
        - "1250:444/tcp"
    monitoring:
      build: ./monitoring
      image: "monitoring"
      container_name: infrac-stak-monitoring
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1260:5666/udp"
        - "1270:5666/tcp"
        - "1280:12489/udp"
        - "1290:12489/tcp"
        - "1300:80/tcp"
        - "1310:443/tcp"    
    no-sql:
      build: ./no-sql
      image: "no-sql"
      container_name: infrac-stak-no-sql
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1320:27017/tcp"
        - "1330:80/tcp"
        - "1340:8081/tcp"
        - "1350:443/tcp"
    servicedesk:
      build: ./servicedesk
      image: "servicedesk"
      container_name: infrac-stak-servicedesk
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1360:80/tcp"
        - "1370:443/tcp"
        - "1380:3306/tcp"
    sql:
      build: ./sql
      image: "sql"
      container_name: infrac-stak-sql
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1390:80/tcp"
        - "1400:3306/tcp"
        - "1410:33060/tcp"
    web-server:
      build: ./web-server
      image: "web-server"
      container_name: infrac-stak-web-server
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1420:80/tcp"
        - "1421:9999/tcp"
        - "1430:443/tcp"
    webmin:
      build: ./webmin
      image: "webmin"
      container_name: infrac-stak-webmin
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1440:80/tcp"
        - "1450:139/tcp"
        - "1460:443/tcp"
    wiki:
      build: ./wiki
      image: "wiki"
      container_name: infrac-stak-wiki
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1470:80/tcp"
        - "1480:443/tcp"