version: '3'
services:
    boards:
      build: ./boards
      image: "boards"
      container_name: infrac-stak-board
      restart: unless-stopped
      stdin_open: true
      tty:  true
      privileged: false
      ports:
        - "1000:80/tcp"
        - "1001:443/tcp"
    ci:
      build: ./ci
      image: "ci"
      container_name: infrac-stak-ci
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
       - ACCEPT_EULA=Y
      ports:
        - "1005:8080/tcp"
        - "1006:443/tcp"
    dhcp:
      build: ./dhcp
      image: "dhcp"
      container_name: infrac-stak-dhcp
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1010:67/udp"
        - "1020:68/udp"
    dns:
      build: ./dns
      image: "dns"
      container_name: infrac-stak-dns
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1030:53/tcp"
        - "1031:56/tcp"
        - "1032:8080/tcp"
    firewall:
      build: ./firewall
      image: "firewall"
      container_name: infrac-stak-firewall
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1040:75/tcp"
    git:
      build: ./git
      image: "git"
      container_name: infrac-stak-git
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1050:3306/tcp"
        - "1060:22/tcp"
        - "1070:80/tcp"
        - "1080:443/tcp"
    java-server:
      build: ./java-server
      image: "java-server"
      container_name: infrac-stak-java-server
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "1090:8080/tcp"
        - "1100:8443/tcp"
    ldap:
      build: ./ldap
      image: "ldap"
      container_name: infrac-stak-ldap
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "2000:389/tcp"
        - "2010:636/tcp"
    logging:
      build: ./logging
      image: "logging"
      container_name: infrac-stak-logging
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "2020:80/tcp"
        - "2021:443/tcp"
        - "2022:27017/tcp"
        - "2023:444/tcp"
    monitoring:
      build: ./monitoring
      image: "monitoring"
      container_name: infrac-stak-monitoring
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "2030:5666/udp"
        - "2031:5666/tcp"
        - "2032:12489/udp"
        - "2033:12489/tcp"
        - "2035:80/tcp"
        - "2036:443/tcp"    
    no-sql:
      build: ./no-sql
      image: "no-sql"
      container_name: infrac-stak-no-sql
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "2040:27017/tcp"
        - "2041:80/tcp"
        - "2042:443/tcp"
    servicedesk:
      build: ./servicedesk
      image: "servicedesk"
      container_name: infrac-stak-servicedesk
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "2050:80/tcp"
        - "2060:443/tcp"
        - "2070:3306/tcp"
    sql:
      build: ./sql
      image: "sql"
      container_name: infrac-stak-sql
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "2080:3306/tcp"
        - "2090:33060/tcp"
    web-server:
      build: ./web-server
      image: "web-server"
      container_name: infrac-stak-web-server
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "2100:80/tcp"
        - "2110:443/tcp"
    webmin:
      build: ./webmin
      image: "webmin"
      container_name: infrac-stak-webmin
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "3000:80/tcp"
        - "3010:139/tcp"
        - "3020:445/tcp"
    wiki:
      build: ./wiki
      image: "wiki"
      container_name: infrac-stak-wiki
      restart: unless-stopped
      stdin_open: true
      tty:  true
      environment:
        - ACCEPT_EULA=Y
      ports:
        - "3040:80/tcp"
        - "3050:443/tcp"